{% set name = "bidsschematools" %}
{% set version = "1.1.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72e73bde5cb4d6f1dd048dc6fa94d4d778cc0e296e8f4c142d3ef85a3c16e6eb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bst = bidsschematools.__main__:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pdm-backend
    - acres
    - pyyaml
  run:
    - python >={{ python_min }}
    - click
    - pyyaml
    - acres

test:
  requires:
    - python {{ python_min }}
    - pip
    - jq
  source_files:
    - pyproject.toml
  imports:
    - bidsschematools
  commands:
    - pip check
    - bst --help
    - bst export | jq '[.bids_version, .schema_version]'
    - pip install "bidsschematools[tests]"
    - python -m pytest -vv --pyargs bidsschematools

about:
  home: https://github.com/bids-standard/bids-specification
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python tools for working with the BIDS schema
  dev_url: https://github.com/bids-standard/bids-specification

extra:
  recipe-maintainers:
    - yarikoptic
    - TheChymera
    - effigies
