{% set name = "bidsschematools" %}
{% set version = "1.0.7" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9091bfd46aaa3a9990fbdbefe28ba105ff1ccc4c0ea01dd9f1ed1113022a1fc2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bst = bidsschematools.__main__:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pdm
  run:
    - python >={{ python_min }}
    - click
    - pyyaml
    - acres

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - pyproject.toml
  imports:
    - bidsschematools
  commands:
    - pip check
    - bst --help
    - python -m pytest -vv --pyargs bidsschematools

about:
  home: https://github.com/bids-standard/bids-specification
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python tools for working with the BIDS schema
  dev_url: https://github.com/bids-standard/bids-specification

extra:
  recipe-maintainers:
    - jwodder
    - yarikoptic
    - TheChymera
    - effigies
