{% set name = "bidsschematools" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1af477a4e5d799da631f6c5d2feb6b84b5ba65db13a4459474d525550e20157a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - bst = bidsschematools.__main__:cli

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - click
    - pyyaml
    - importlib-resources
    - jsonschema
    - tabulate
    - pandas
    - pyparsing
    - markdown-it-py

test:
  requires:
    - pip
    - pytest
  source_files:
    - pyproject.toml
  imports:
    - bidsschematools
  commands:
    - pip check
    - bst --help
    - python -m pytest -vv --pyargs bidsschematools

about:
  home: https://github.com/bids-standard/bids-specification
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python tools for working with the BIDS schema
  dev_url: https://github.com/bids-standard/bids-specification

extra:
  recipe-maintainers:
    - jwodder
    - yarikoptic
    - TheChymera
    - effigies
